sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123123
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tAcSpFEhtjsoLfe1GR3
    access-key-secret: BWmHXJCUOUIMzMgkNA4XLnVkh2yEvj
    bucket-name: web-deemo
  redis:
    host: localhost
    port: 6379
    database: 10